# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_story_instagram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Kare görsel. Önerilen 1200×1200 px (en az 800×800). JPG veya WebP, mümkünse 2 MB altı.",
                null=True,
                upload_to="products/",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                help_text="Ana görsel ile aynı: kare 1200×1200 px, JPG/WebP, 2 MB altı.",
                upload_to="products/gallery/",
            ),
        ),
    ]
