# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_product_image_help"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Varyant yoksa bu fiyat kullanılır (TL).",
                max_digits=10,
            ),
        ),
    ]
